### ISSUE TITLE
add the documentation on how to run the site locally

### ISSUE THREAD

**Issue by lucadonnoh** [yieldfarming/yield-farming#35]
include in the README the documentation on how to run the site locally

**Comment by chppppp** [comment]
I imagine they will close this because the guys pinned tweet is literally 'i make tools for people who know how to use them'. 

look up modern react courses like codewithmosh or https://platform.ui.dev/ and learn some javascript before trying to host this locally. i am 1100% sure the author doesnt want to be responsible for dealing with this kind of stuff.

**Comment by lucadonnoh** [comment]
ok thanks, i know js i just dont know how to run react

**Comment by chppppp** [comment]
ill do u a solid, dont say i never did anything for you
```
npm install
npm build
npm start
```

**Comment by penandlim** [comment]
You can just run 

`npm run dev` to run dev build
`npm run build` to create dist/ folder which can be used to serve as static website.
